// Embeds src/styles.css as a string module so the components can inject their
// own styles — consumers then don't need to import the CSS file themselves.
import { readFileSync, writeFileSync } from 'node:fs';

const css = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const out = `// Generated by scripts/embed-css.mjs from styles.css — do not edit.\nexport const css = ${JSON.stringify(css)};\n`;
writeFileSync(new URL('../src/utils/stylesText.ts', import.meta.url), out);
